import{a as d,S as L,i}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const w="52950914-a47a655b15acf3b435807e601";d.defaults.baseURL="https://pixabay.com/api/";async function m(e,t=1){try{return(await d.get("",{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(a){throw console.error("Error fetching images:",a),a}}let S=new L(".gallery a",{captionDelay:250,enableKeyboard:!0,showCounter:!0,scrollZoom:!0,loop:!0,overlayOpacity:.9,animationSpeed:250});const f=document.querySelector(".loader");function y(){f.classList.add("visible")}function u(){f.classList.remove("visible")}function q(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function v(e){return e.map(({previewURL:t,largeImageURL:a,tags:l,likes:r,views:o,comments:n,downloads:b})=>`<li class="gallery__item">
                <a class="gallery__link" href="${a}">
                    <img class="gallery__image" src="${t}" alt="${l}" />
                    <div class="info">
                        <p><b>Likes:</b> ${r}</p>
                        <p><b>Views:</b> ${o}</p>
                        <p><b>Comments:</b> ${n}</p>
                        <p><b>Downloads:</b> ${b}</p>
                    </div>
                </a>
            </li>`).join("")}function g(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",v(e)),S.refresh()}const h=document.querySelector(".load-more-hidden");function _(){h.classList.replace("load-more-hidden","load-more")}function p(){h.classList.replace("load-more","load-more-hidden")}let s=1,c="";const M=document.querySelector(".form"),E=document.querySelector(".load-more-hidden");document.querySelector(".gallery");M.addEventListener("submit",P);E.addEventListener("click",$);async function P(e){if(e.preventDefault(),c=e.currentTarget.elements["search-text"].value.trim(),!c){i.error({title:"Error",message:"Please enter a search query!"});return}q(),s=1,y(),p();try{const t=await m(c,s);if(u(),t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t.hits),_()}catch(t){u(),console.error("Error fetching images:",t),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."})}}async function $(){s++,y();try{const e=await m(c,s);if(u(),s>=Math.ceil(e.totalHits/15)){p(),i.info({title:"Info",message:"We're sorry, but you've reached the end of the search results."});return}g(e.hits),B()}catch{u(),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."})}}function B(){const e=document.querySelector(".gallery .gallery__item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
